#!/bin/sh

WILDFLY_BASE_URL="https://github.com/wildfly/wildfly/releases/download"
WILDFLY_BASE_URL_DOWNLOAD="https://www.wildfly.org/downloads/"

wildfly()
{
  if [ $VERSION != "latest" ]
  then
    VERSION=$( curl ${WILDFLY_BASE_URL_DOWNLOAD} 2>/dev/null \
      | egrep -i \.zip \
      | egrep -ow '"(http?(s)://.*.zip)"' \
      | egrep -o 'wildfly-[0-9]{1,}.(.[0-9]){1,}?.?(Final).zip' \
      | sort \
      | uniq \
      | egrep -o '[0-9]{1,}(.[0-9]){1,}' \
      | egrep "${VERSION}"
    )
  else
     VERSION=$( curl ${WILDFLY_BASE_URL_DOWNLOAD} 2>/dev/null \
      | egrep -i \.zip \
      | egrep -ow '"(http?(s)://.*.zip)"' \
      | egrep -o 'wildfly-[0-9]{1,}.(.[0-9]){1,}?.?(Final).zip' \
      | sort \
      | uniq \
      | egrep -o '[0-9]{1,}(.[0-9]){1,}' \
      | tail -1
    )
  fi
  echo "wildfly-${VERSION}.Final.zip"
  curl -OL --progress-bar "${WILDFLY_BASE_URL}/${VERSION}.Final/wildfly-${VERSION}.Final.zip"
  if [ $DOWNLOADONLY -eq 0 ]
  then
    extract "wildfly-${VERSION}.Final.zip"
    start "wildfly-${VERSION}.Final"
    cleanup
  fi
}

extract() {

  cat > wildfly-extract.sh <<EOF
mkdir -p /tmp/install.$$
mv "$1" /tmp/install.$$
cd /tmp/install.$$
unzip /tmp/install.$$/$1
EOF

sh wildfly-extract.sh
rm -f wildfly-extract.sh

}

start()
{
  /tmp/install.$$/$1/bin/standalone.sh
}

cleanup()
{
  rm -f /tmp/install.$$
}

main()
{
  [ $# -eq 0 ] && wildfly

  while [ $# -ne 0 ]
  do
    case $1 in
       "-i")
         read -p "Qual versão do WildFly você deseja fazer download: " VERSION
       ;;
       "-v")
         shift
         VERSION=$1
       ;;
       "-d")
         DOWNLOADONLY=1
       ;;
    esac
    shift
  done

  wildfly "${VERSION:=latest} ${DOWNLOADONLY:=0}"
  exit 0
}

main $@
